course/urls.py
from django.urls import path, include

from .views import CourseViews, LessonViews, ThanksYouViews, CommentCreate

app_name = 'course'
urlpatterns = [
    path('<course_id>/', CourseViews.as_view(), name='course'),
    path('<course_id>/thanksyou/', ThanksYouViews.as_view(), name='thanksyou'),
    path('<course_id>/lesson_<lesson_id>', LessonViews.as_view(), name='lesson'),
    path('<course_id>/create-comment/', CommentCreate.as_view(), name='create-comment'),
]

online_learning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from core.views import IndexView, ProfileView, StudentsView, Custom404View, Custom403View, Custom500View
from register import views as v
from core import views as edit_view

handler404 = Custom404View.as_view()
handler403 = Custom403View.as_view()
#handler500 = Custom500View.as_view()

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', IndexView.as_view(), name='home'),
    path('catalog/', include('catalog.urls'), name='catalog'),
    path('course/', include('course.urls')),

    # new user register
    path('register/', v.register, name='register'),
    # user login
    path('', include("django.contrib.auth.urls")),
    # social account login
    path('accounts/', include('allauth.urls')),

    # user profile and edit
    path('profile/', ProfileView.as_view()),
    path('profile/edit/', edit_view.profile_edit, name='profile_edit'),
    # path('profile/edit/', ProfileEditView.as_view())

    # all students page
    path('students/', StudentsView.as_view())
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

course/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User


class Lesson(models.Model):
	name = models.CharField(max_length=100)
	description = models.TextField()
	video = models.URLField(max_length=250)
	homework = models.TextField(null=True)
	completed_by = models.ManyToManyField(User, blank=True, default=None)

	def __str__(self):
		return self.name


class Category(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name


class Course(models.Model):
	name = models.CharField(max_length=30)
	description = models.TextField()
	category = models.ForeignKey(Category, on_delete=models.PROTECT)
	cost = models.IntegerField(default=50, validators=[MinValueValidator(50)])
	lessons = models.ManyToManyField('Lesson', blank=True)
	purchased_by = models.ManyToManyField(User, blank=True, related_name='users')
	completed_by = models.ManyToManyField(User, blank=True, default=None)

	def __str__(self):
		return self.name


class Comment(models.Model):
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	autor = models.CharField(max_length=30)
	text = models.TextField()

	def __str__(self):
		return self.autor

course/views.py
import stripe

from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.shortcuts import render

from .models import Course, Lesson

stripe.api_key = settings.STRIPE_SECRET_KEY


class CourseViews(TemplateView):
	template_name = '403/index.html'

	def get(self, request, course_id, **kwargs):
		try:
			course = Course.objects.filter(id=course_id).select_related('category').prefetch_related('lessons', 'purchased_by')[0]
			comments = course.comment_set.all()

			if request.user in course.purchased_by.all():
				context = super().get_context_data(**kwargs)
				context['course'] = course
				context['comments'] = comments
				context["completed_courses"] = Course.objects.filter(completed_by__username=self.request.user)

				return render(request, 'course/course.html', context)

			else:
				context = super().get_context_data(**kwargs)
				context['key'] = settings.STRIPE_PUBLISHABLE_KEY
				context['course'] = course
				context['comments'] = comments

				return render(request, 'course/payment_page.html', context)
		
		except IndexError:
			return render(request, '404/index.html')


class LessonViews(TemplateView):
	template_name = '403/index.html'

	def get(self, request, course_id, lesson_id):
		try:
			course = Course.objects.filter(id=course_id).prefetch_related('lessons', 'purchased_by')[0]
			completed_lessons = Lesson.objects.filter(completed_by__username=self.request.user)

			if request.user in course.purchased_by.all():
				lesson = course.lessons.filter(id=lesson_id)[0]

				return render(request, 'course/lesson.html', {'course_id': course_id, 'lesson': lesson, 'completed_lessons': completed_lessons})

			else:
				return render(request, self.template_name)

		except IndexError:
			return render(request, '404/index.html')


class ThanksYouViews(TemplateView):
	template_name = '403/index.html'

	def post(self, request, course_id):

		course = Course.objects.filter(id=course_id).prefetch_related('purchased_by')[0]

		course.purchased_by.add(request.user)
		course.save()

		charge = stripe.Charge.create(
            amount=course.cost,
            currency='usd',
            description=f'Buy course with id = {course_id}',
            source=request.POST['stripeToken']
        )

		return render(request, 'course/thankyou.html')


class CommentCreate(TemplateView):
	template_name = '403/index.html'

	def post(self, request, course_id):
		course = Course.objects.filter(id=course_id).select_related('category').prefetch_related('lessons', 'purchased_by')[0]

		if request.POST['text'].replace(" ", ""):
			course.comment_set.create(autor=request.user.username, text=request.POST['text'])
			course.save()

		else:
			pass

		return HttpResponseRedirect(reverse('course:course', args=(course_id,)))

templates/course/comments.html
<br />

<div class='block'>

	{% if not comments %}
		<p>There are no comments for this course yet.</p>
	{% endif %}

	{% if request.user.is_authenticated %}
		<form action="{% url 'course:create-comment' course.id %}" method="post">
			{% csrf_token %}
			<label for="exampleFormControlTextarea1">Input comment: </label>
	    	<textarea class="form-control" id="exampleFormControlTextarea1" rows="5" name="text"></textarea>

	    	<button type="submit" class="btn btn-primary" >Create</button>
		</form>
	{% else %}
		<a class="btn btn-primary" href="/login/" role="button">Login</a>
	{% endif %}

	{% if comments %}
		{% for comment in comments %}
			<br />
			<div class="card">
			  <div class="card-header">
			    <h2>{{ comment.autor }}</h2>
			  </div>
			  <div class="card-body">
			    <blockquote class="blockquote mb-0">
			      <p>{{ comment.text }}</p>
			    </blockquote>
			  </div>
			</div>
		{% endfor %}
	{% endif %}
</div>

templates/course/course.html
{% extends 'base.html' %}

{% block title %}
	Course
{% endblock %}

{% block content %}
	{% if course %}
		<div class="jumbotron jumbotron-fluid">
		  <div class="container">

		    <h1 class="display-4">{{ course.name }}</h1>
			  {% if course in completed_courses %}
			  <p align="right" style="color:green"><b>Congratulations! Course completed!</b></p>
			  {% else %}
			  <p align="right" style="color:orange"><b>You have not completed this course yet.</b></p>
			  {% endif %}

			<span class="badge badge-primary badge-pill">{{ course.category }}</span>

		    <p class="lead">{{ course.description }}</p>

		    <hr class="my-4">
			
			<h3>LESSONS:</h3>
			<ul class="list-group">
				{% for lesson in course.lessons.all %}
					<li class="list-group-item"><a href="{% url 'course:lesson' course.id lesson.id  %}">{{ lesson.name }}</a></li>
				{% endfor %}
			</ul>

			<hr class="my-4">

			<h3>COMMENTS:</h3>

			<div class="comments">
				{% include "course/comments.html" %}
			</div>

		  </div>
		</div>
	{% endif %}
{% endblock %}

templates/course/lesson.html
{% extends 'base.html' %}

{% block title %}
	Course
{% endblock %}

{% block content %}

	<div class="jumbotron jumbotron-fluid">
		  <div class="container">

		    <h1 class="display-4 text-center">{{ lesson.name }}</h1>
			  {% if lesson in completed_lessons %}
			  <p style="color:green" align="center"><b>Lesson is completed</b></p>
			  {% else %}
			  <p style="color:orange" align="center">Lesson is not completed</p>
			  {% endif %}

			<div class="card">
			  <div class="card-body">
			    {{ lesson.description }}
			  </div>
			</div>
			
			<hr class="my-4">

		    <p class="lead text-center">
		    	<iframe width="800" height="512"
					src="{{ lesson.video }}">
				</iframe>
		    </p>

		    <hr class="my-4">

		    <div class="card">

			  <div class="card-header">
			    Homework
			  </div>

			  <div class="card-body">
			    <blockquote class="blockquote mb-0">
			      <p>{{ lesson.homework }}</p>
			    </blockquote>
			  </div>
			</div>			

		  </div>
		</div>

{% endblock %}

templates/course/payment_page.html
{% extends 'base.html' %}

{% block title %}
	Course
{% endblock %}

{% block content %}
	{% if course %}
		<div class="jumbotron jumbotron-fluid">
		  <div class="container">

		    <h1 class="display-4">{{ course.name }}</h1>

			<span class="badge badge-primary badge-pill">{{ course.category }}</span>

		    <p class="lead">{{ course.description }}</p>
			
			{% if request.user.is_authenticated %}
			    <form action="thanksyou/" method="post">
				  	{% csrf_token %}
				 	<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
				          data-key="{{ key }}"
				          data-description="Buy course"
				          data-amount="{{ course.cost }}"
				          data-locale="auto"></script>
				</form>
			{% else %}
				<a class="btn btn-primary" href="/login/" role="button">Login</a>
			{% endif %}

		    <hr class="my-4">
			
			<h3>LESSONS:</h3>
			<ul class="list-group">
				{% for lesson in course.lessons.all %}
					<li class="list-group-item">{{ lesson.name }}</li>
				{% endfor %}
			</ul>

			<hr class="my-4">

			<h3>COMMENTS:</h3>

			<div class="comments">
				{% include "course/comments.html" %}
			</div>		

		  </div>
		</div>
	{% endif %}
{% endblock %}

templates/course/thankyou.html
{% extends 'base.html' %}

{% block title %}
	Thanks you
{% endblock %}

{% block content %}
	<div class="jumbotron jumbotron-fluid">
		<div class="container text-center">

			<h6>Thank you</h6>

		</div>
	</div>
{% endblock %}